### PR TITLE
Fix chainRec tests

### PR DESCRIPTION
**Pull request by Avaq**
I found this while integrating fantasy-laws into Fluture.

### CODE REVIEW

**Comment by davidchambers** [comment]
Excellent! I just discovered this issue myself. :)

There's one other fix I'd like to make before releasing v1.0.1.

**Review by davidchambers — APPROVED** [review]

**Comment by Avaq** [comment]
> There's one other fix I'd like to make

Can I help somehow?

**Comment by davidchambers** [comment]
> Can I help somehow?

You just did. Also, you could review the sanctuary-type-classes pull request I'll open later today. :)

**Comment by Avaq** [comment]
Would you mind releasing a hotfix?

**Comment by davidchambers** [comment]
I finally opened sanctuary-js/sanctuary-type-classes#88. Once that pull request has been reviewed and merged I will release `sanctuary-type-classes@8.1.1`, then update this project to require it.

**Pull request merged**
